package com.findjob.findjobgradle.domain;

public enum Category {
    ADMINISTRATION("ADMINISTRATION"), CONSULTING("CONSULTING"), RESEARCH_AND_0DEVELOPMENT("RESEARCH_AND_0DEVELOPMENT"),
    BANKING("BANKING"), CONSTRUCTION("CONSTRUCTION"),
    CALL_CENTER("CALL_CENTER"), EDUCATION("EDUCATION"),
    FINANCE("FINANCE"), FRANCYZA("FRANCYZA"),
    HOSPITALITY("HOSPITALITY"), INTERNET_ECOMMERCE("INTERNET_ECOMMERCE"),
    ENGINEERING("ENGINEERING"), IT("IT"), MEDIA("MEDIA"),
    CUSTOMER_SERVICE("CUSTOMER_SERVICE"), PHYSICAL_WORK("PHYSICAL_WORK"), LAW("LAW"),
    PRODUCTION("PRODUCTION"), ADVERTISING("ADVERTISING"), PUBLIC_SECTOR("PUBLIC_SECTOR"),
    SALES("SALES"), TRANSPORT("TRANSPORT"), INSURANCE("INSURANCE"),
    SHOPPING("SHOPPING"), QUALITY_CONTROL("QUALITY_CONTROL"),
    ENERGY("ENERGY"), OTHER("OTHER");

    String title;

    Category(String title) {
        this.title = title;
    }

}
